:- module sentence_predicates.
:- interface.
:- import_module mrs.
:- import_module multi_map.

:- type preds ---> pred_unknown(pred(mrs_rel_handle, mrs_unknown, mrs_event))
                 ; pred_person(pred(mrs_rel_handle, mrs_inst))
                 ; pred_pron(pred(mrs_rel_handle, mrs_inst))
                 ; pred_generic_entity(pred(mrs_rel_handle, mrs_inst))
                 ; pred_butler_n_1(pred(mrs_rel_handle, mrs_inst))
                 ; pred_proper_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_some_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_udef_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_the_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_a_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_def_explicit_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_pronoun_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_every_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_no_q(pred(mrs_rel_handle, mrs_inst, mrs_rstr_handle, mrs_body_handle))
                 ; pred_live_v_1(pred(mrs_rel_handle, mrs_event, mrs_inst))
                 ; pred_be_v_id(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
                 ; pred_in_p_loc(pred(mrs_rel_handle, mrs_event, mrs_event, mrs_inst))
                 ; pred_named(pred(mrs_rel_handle, mrs_inst, mrs_carg))
                 ; pred_card(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_carg))
		 ; pred_kill_v_1(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
		 ; pred_killer_n_1(pred(mrs_rel_handle, mrs_inst))
		 ; pred_hate_v_1(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
		 ; pred_compound(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
		 ; pred_implicit_conj(pred(mrs_rel_handle, mrs_inst, mrs_inst, mrs_inst))
		 ; pred_and_c_e(pred(mrs_rel_handle, mrs_event, mrs_event, mrs_event))
		 ; pred_and_c_x(pred(mrs_rel_handle, mrs_inst, mrs_inst, mrs_inst))
		 ; pred_people_n_of(pred(mrs_rel_handle, mrs_inst, mrs_indiv))
		 ; pred_victim_n_of(pred(mrs_rel_handle, mrs_inst, mrs_indiv))
		 ; pred_aunt_n_of(pred(mrs_rel_handle, mrs_inst, mrs_indiv))
		 ; pred_therein_p_dir(pred(mrs_rel_handle, mrs_event, mrs_event))
		 ; pred_only_a_1(pred(mrs_rel_handle, mrs_event, mrs_inst))
		 ; pred_neg(pred(mrs_rel_handle, mrs_event, mrs_rel_handle))
		 ; pred_always_a_1(pred(mrs_rel_handle, mrs_indiv, mrs_event))
		 ; pred_never_a_1(pred(mrs_rel_handle, mrs_indiv, mrs_rel_handle))
		 ; pred_therefore_a_1(pred(mrs_rel_handle, mrs_indiv, mrs_rel_handle))
		 ; pred_rich_a_in(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_indiv))
		 ; pred_more_comp(pred(mrs_rel_handle, mrs_event, mrs_event, mrs_inst))
		 ; pred_poss(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
		 ; pred_except_p(pred(mrs_rel_handle, mrs_event, mrs_inst, mrs_inst))
		 ; pred_colon_p_namely(pred(mrs_rel_handle, mrs_event, mrs_rel_handle, mrs_rel_handle)).

:- inst preds for preds/0 ---> 
	         pred_unknown(pred(out, out, out) is nondet)
	         ; pred_person(pred(out, out) is nondet)
	         ; pred_pron(pred(out, out) is nondet)
	         ; pred_generic_entity(pred(out, out) is nondet)
		 ; pred_butler_n_1(pred(out,out) is nondet)
	         ; pred_proper_q(pred(out, out, out, out) is nondet)
	         ; pred_some_q(pred(out, out, out, out) is nondet)
	         ; pred_udef_q(pred(out, out, out, out) is nondet)
	         ; pred_the_q(pred(out, out, out, out) is nondet)
	         ; pred_a_q(pred(out, out, out, out) is nondet)
	         ; pred_def_explicit_q(pred(out, out, out, out) is nondet)
                 ; pred_every_q(pred(out,out,out,out) is nondet)
	         ; pred_pronoun_q(pred(out, out, out, out) is nondet)
	         ; pred_no_q(pred(out, out, out, out) is nondet)
                 ; pred_live_v_1(pred(out, out, out) is nondet)
                 ; pred_be_v_id(pred(out, out, out, out) is nondet)
                 ; pred_in_p_loc(pred(out,out,out,out) is nondet)
                 ; pred_named(pred(out,out,out) is nondet)
                 ; pred_card(pred(out,out,out,out) is nondet)
		 ; pred_kill_v_1(pred(out,out,out,out) is nondet)
		 ; pred_killer_n_1(pred(out,out) is nondet)
		 ; pred_hate_v_1(pred(out,out,out,out) is nondet)
		 ; pred_compound(pred(out,out,out) is nondet)
		 ; pred_implicit_conj(pred(out,out,out,out) is nondet)
		 ; pred_and_c_e(pred(out,out,out) is nondet)
		 ; pred_and_c_x(pred(out,out,out) is nondet)
		 ; pred_people_n_of(pred(out,out, out) is nondet)
		 ; pred_victim_n_of(pred(out,out, out) is nondet)
		 ; pred_aunt_n_of(pred(out,out, out) is nondet)
		 ; pred_therein_p_dir(pred(out,out,out) is nondet)
		 ; pred_only_a_1(pred(out,out) is nondet)
		 ; pred_neg(pred(out,out,out) is nondet)
		 ; pred_always_a_1(pred(out,out) is nondet)
		 ; pred_never_a_1(pred(out,out) is nondet)
		 ; pred_therefore_a_1(pred(out,out) is nondet)
		 ; pred_rich_a_in(pred(out,out,out,out) is nondet)
		 ; pred_more_comp(pred(out,out,out,out) is nondet)
		 ; pred_poss(pred(out,out,out,out) is nondet)
		 ; pred_except_p(pred(out,out,out,out) is nondet)
		 ; pred_colon_p_namely(pred(out,out,out,out) is nondet).

:- implementation.

